### PR TITLE
Some font changes, spacing adjustments, bottom margin adjustments

### PR DESCRIPTION
**Pull request by kiatlim**

### CODE REVIEW

**Comment by kiatlim** [comment]
[1536211744.pdf](https://github.com/unee-t/inspectionreportgenerator/files/2355551/1536211744.pdf)

**Comment by franck-boullier** [comment]
This looks great!

Attached are the version printed with the Primo PDF printer emulator and the scan of the version printed on an HP printer: both looks fine, page number are visible. 
Issue #7 is fixed in that version

[primo_pdf_printer_emulator_1536211744_v4.pdf](https://github.com/unee-t/inspectionreportgenerator/files/2355717/primo_pdf_printer_emulator_1536211744_v4.pdf)
[scan_of_a_print_1536211744_v4.pdf](https://github.com/unee-t/inspectionreportgenerator/files/2355718/scan_of_a_print_1536211744_v4.pdf)

Not sure why travis in complaining though...

**Comment by kaihendry** [comment]
Can't merge this. There is a _compareTemp/TMPHGBWNE.html, *.xml and a .DS_Store that shouldn't be in the patch.

**Comment by kiatlim** [comment]
@kaihendry Removed the unnecessary files.

**Pull request merged**
